server:
  port: 8004
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/curryQin/Spring-Cloud-Config     # 配置git仓库的地址
          search-paths: config                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password: